CREATE SCHEMA IF NOT EXISTS stg;

CREATE TABLE IF NOT EXISTS stg.stg_cbo (
    cod     INT,
    nome    TEXT
);

CREATE TABLE IF NOT EXISTS stg.stg_cid10_capitulos (
	codigo          text,
	descricao       text,
	descricao_breve text
);

CREATE TABLE IF NOT EXISTS stg.stg_cid10_categorias (
	cat           	text,
	classif       	text,
	descricao     	text,
	descrabrev    	text,
	refer         	text,
	excluidos     	float,
	"unnamed: 6"    float
);

CREATE TABLE IF NOT EXISTS stg.stg_cid10_subcategorias (
	subcat        	text,
	classif       	text,
	restrsexo     	text,
	causaobito    	text,
	descricao     	text,
	descrabrev    	text,
	refer         	text,
	excluidos     	text,
	"unnamed: 8"    float
);

CREATE TABLE IF NOT EXISTS stg.stg_municipios (
	"municipio-id"				int,
	"municipio-nome"			text,
	"microrregiao-id"			int,
	"microrregiao-nome"			text,
	"mesorregiao-id"			int,
	"mesorregiao-nome"			text,
	"regiao-imediata-id"		int,
	"regiao-imediata-nome"		text,
	"regiao-intermediaria-id"	int,
	"regiao-intermediaria-nome"	text,
	"uf-id"						int,
	"uf-sigla"					text,
	"uf-nome"					text,
	"regiao-id"					int,
	"regiao-sigla"				text,
	"regiao-nome"				text
);

CREATE TABLE IF NOT EXISTS stg.stg_ocupacao (
	cod     int,
	nome    text
);

CREATE TABLE IF NOT EXISTS stg.stg_pais (
	"pais-m49"					int,
	"pais-iso-alpha-2"			text,
	"pais-iso-alpha-3"			text,
	"pais-nome"					text,
	"regiao-intermediaria-m49"	int,
	"regiao-intermediaria-nome"	text,
	"sub-regiao-m49"			int,
	"sub-regiao-nome"			text,
	"regiao-m49"				int,
	"regiao-nome"				text
);

CREATE TABLE IF NOT EXISTS stg.stg_tb_sigtab (
	cod     int,
	"value"	text
);

CREATE TABLE IF NOT EXISTS stg.stg_leitos (
	cod     int,
	"value"	text
);

CREATE TABLE IF NOT EXISTS stg.stg_sim (
	contador    text,
	origem      text,
	tipobito    text,
	dtobito     text,
	horaobito   text,
	"natural"   text,
	dtnasc      text,
	idade       text,
	sexo        text,
	racacor     text,
	estciv      text,
	esc         text,
	ocup        text,
	codmunres   text,
	codbaires   text,
	lococor     text,
	codestab    text,
	codmunocor  text,
	codbaiocor  text,
	idademae    text,
	escmae      text,
	ocupmae     text,
	qtdfilvivo  text,
	qtdfilmort  text,
	gravidez    text,
	gestacao    text,
	parto       text,
	obitoparto  text,
	peso        text,
	obitograv   text,
	obitopuerp  text,
	assistmed   text,
	exame       text,
	cirurgia    text,
	necropsia   text,
	linhaa      text,
	linhab      text,
	linhac      text,
	linhad      text,
	linhaii     text,
	causabas    text,
	dtatestado  text,
	circobito   text,
	acidtrab    text,
	fonte       text,
	tppos       text,
	dtinvestig  text,
	causabas_o  text,
	dtcadastro  text,
	atestante   text,
	fonteinv    text,
	dtrecebim   text,
	ufinform    text,
	cb_pre      text,
	morteparto  text,
	dtcadinf    text,
	tpobitocor  text,
	dtcadinv    text,
	comunsvoim  text,
	dtrecorig   text,
	dtrecoriga  text,
	causamat    text,
	esc2010     text,
	escmae2010  text,
	stdoepidem  text,
	stdonova    text,
	semagestac  text,
	tpmorteoco  text,
	difdata     text,
	dtconcaso   text,
	nudiasobin  text,
	seriescfal  text,
	seriescmae  text,
	codmuncart  text,
	codcart     text,
	numregcart  text,
	dtregcart   text,
	dtconinv    text,
	codmunnatu  text,
	estabdescr  text,
	crm         text,
	numerolote  text,
	stcodifica  text,
	codificado  text,
	versaosist  text,
	versaoscb   text,
	atestado    text,
	escmaeagr1  text,
	escfalagr1  text,
	nudiasobco  text,
	fontes      text,
	tpresginfo  text,
	tpnivelinv  text,
	nudiasinf   text,
	fontesinf   text,
	altcausa    text
);

CREATE TABLE IF NOT EXISTS stg.stg_uf (
	"uf-id"			INT,
	"uf-sigla"		TEXT,
	"uf-nome"		TEXT,
	"regiao-id"		INT,
	"regiao-sigla"	TEXT,
	"regiao-nome"	TEXT
);

CREATE TABLE IF NOT EXISTS stg.stg_sih (
    uf_zi       TEXT,
    ano_cmpt    TEXT,
    mes_cmpt    TEXT,
    espec       TEXT,
    cgc_hosp    TEXT,
    n_aih       TEXT,
    ident       TEXT,
    cep         TEXT,
    munic_res   TEXT,
    nasc        TEXT,
    sexo        TEXT,
    uti_mes_in  TEXT,
    uti_mes_an  TEXT,
    uti_mes_al  TEXT,
    uti_mes_to  TEXT,
    marca_uti   TEXT,
    uti_int_in  TEXT,
    uti_int_an  TEXT,
    uti_int_al  TEXT,
    uti_int_to  TEXT,
    diar_acom   TEXT,
    qt_diarias  TEXT,
    proc_solic  TEXT,
    proc_rea    TEXT,
    val_sh      TEXT,
    val_sp      TEXT,
    val_sadt    TEXT,
    val_rn      TEXT,
    val_acomp   TEXT,
    val_ortp    TEXT,
    val_sangue  TEXT,
    val_sadtsr  TEXT,
    val_transp  TEXT,
    val_obsang  TEXT,
    val_ped1ac  TEXT,
    val_tot     TEXT,
    val_uti     TEXT,
    us_tot      TEXT,
    dt_inter    TEXT,
    dt_saida    TEXT,
    diag_princ  TEXT,
    diag_secun  TEXT,
    cobranca    TEXT,
    natureza    TEXT,
    nat_jur     TEXT,
    gestao      TEXT,
    rubrica     TEXT,
    ind_vdrl    TEXT,
    munic_mov   TEXT,
    cod_idade   TEXT,
    idade       TEXT,
    dias_perm   TEXT,
    morte       TEXT,
    nacional    TEXT,
    num_proc    TEXT,
    car_int     TEXT,
    tot_pt_sp   TEXT,
    cpf_aut     TEXT,
    homonimo    TEXT,
    num_filhos  TEXT,
    instru      TEXT,
    cid_notif   TEXT,
    contracep1  TEXT,
    contracep2  TEXT,
    gestrisco   TEXT,
    insc_pn     TEXT,
    seq_aih5    TEXT,
    cbor        TEXT,
    cnaer       TEXT,
    vincprev    TEXT,
    gestor_cod  TEXT,
    gestor_tp   TEXT,
    gestor_cpf  TEXT,
    gestor_dt   TEXT,
    cnes        TEXT,
    cnpj_mant   TEXT,
    infehosp    TEXT,
    cid_asso    TEXT,
    cid_morte   TEXT,
    complex     TEXT,
    financ      TEXT,
    faec_tp     TEXT,
    regct       TEXT,
    raca_cor    TEXT,
    etnia       TEXT,
    sequencia   TEXT,
    remessa     TEXT,
    aud_just    TEXT,
    sis_just    TEXT,
    val_sh_fed  TEXT,
    val_sp_fed  TEXT,
    val_sh_ges  TEXT,
    val_sp_ges  TEXT,
    val_uci     TEXT,
    marca_uci   TEXT,
    diagsec1    TEXT,
    diagsec2    TEXT,
    diagsec3    TEXT,
    diagsec4    TEXT,
    diagsec5    TEXT,
    diagsec6    TEXT,
    diagsec7    TEXT,
    diagsec8    TEXT,
    diagsec9    TEXT,
    tpdisec1    TEXT,
    tpdisec2    TEXT,
    tpdisec3    TEXT,
    tpdisec4    TEXT,
    tpdisec5    TEXT,
    tpdisec6    TEXT,
    tpdisec7    TEXT,
    tpdisec8    TEXT,
    tpdisec9    TEXT
);