from stg.STG_SIM import run_sim
from stg.STG_SIH import run_sih
from stg.STG_UF import run_stg_uf
from stg.STG_CBO import run_stg_cbo
from stg.STG_PAIS import run_stg_pais
from stg.STG_LEITOS import run_stg_leitos
from stg.STG_OCUPACAO import run_stg_ocupacao
from stg.STG_TB_SIGTAB import run_stg_tb_sigtab
from stg.STG_MUNICIPIOS import run_stg_municipios
from stg.STG_CID10_CAPITULOS import run_cid10_capitulos
from stg.STG_CID10_CATEGORIAS import run_cid10_categorias
from stg.STG_CID10_SUBCATEGORIAS import run_cid10_subcategorias