# docker commands to prompt
# docker pull postgres
# docker run --name postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d -v postgres-volume:/var/lib/postgresql/data postgres:latest

# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432